trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r src/requirements.txt
    python -m flask --version
  displayName: 'Install dependencies and verify Flask version'

- task: Docker@2
  inputs:
    containerRegistry: 'webappcicd-acr'
    repository: 'webappcicd.azurecr.io/flask-app'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)
    context: $(Build.SourcesDirectory)

- task: AzureCLI@2
  inputs:
    azureSubscription: 'webappcicd'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
     az webapp config container set --name webappcicd --resource-group ResourceGroup2 --docker-custom-image-name webappcicd.azurecr.io/flask-app:$(Build.BuildId)
  displayName: 'Deploy to Azure App Service'

